### ISSUE TITLE
[BUG] - Side sheet in combinatie met Vlaamse header is niet OK

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-side-sheet#46]
**Omschrijf het probleem**
Op de demo pagina zie je dat de side sheet achter te header komt te zitten

**Hoe te reproduceren**
Ga naar demo pagina: https://webcomponenten.omgeving.vlaanderen.be/demo/vl-side-sheet.html

**Gewenst gedrag**
Side sheet die zich aanpast aan header.

**Screenshots**
https://webcomponenten.omgeving.vlaanderen.be/demo/vl-side-sheet.html
<img width="582" alt="image" src="https://user-images.githubusercontent.com/29454303/93089016-fc820f80-f69a-11ea-9258-63fe8c529092.png">

**Omgeving (gelieve aan te vullen):**
 - Browser chrome, Fx
 - Versie 85, 81
 - Versie component 3.0.6

**Extra info**
Pas relevant als Vlaamse header bruikbaar is

**Comment by coemans** [comment]
@driesva in de side-sheet kan best gebruikt worden van de vl-region > vl-layout > vl-grid (optioneel). Ik zal de demo aanpassen zodat dit voor afnemers duidelijk is. Wanneer deze componenten gebruikt worden, zal de rendering wel OK zijn.

**Comment by driesva** [comment]
OK, als het zo werkt en gedocumenteerd is, prima voor mij.

**Comment by coemans** [comment]
@driesva er zullen vermoedelijk toch enkele stijl wijzigingen uitgevoerd moeten worden bijvoorbeeld combinatie met vl-layout omdat deze een min-width heeft. Ik voorzie alvast in de demo een code voorbeeld.
