### ISSUE TITLE
[BUG] - sluit knop is toggle knop geworden die men niet kan verbergen

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-side-sheet#59]
**Omschrijf het probleem**
Voor discussie vatbaar of het een feature request of bug is, maar voor onze applicatie is het een regressie in de manier waarop de side sheet werkt.

Voorheen (in versie 1.0.1) had de side sheet een sluit knop:
![image](https://user-images.githubusercontent.com/29454303/103336361-38898680-4a78-11eb-8c08-81597a83e18a.png)

Sinds de upgrade (versie 3.1.2) blijkt dit een _toggle_ knop te zijn geworden. Het probleem in onze context is dat deze knop nu altijd zichtbaar is en de gebruiker hiermee de side sheet (ongewenst) kan openen:
![image](https://user-images.githubusercontent.com/29454303/103338609-3a0a7d00-4a7f-11eb-9f5a-1d7aa23e3f63.png)
maar als je de site sheet openklapt krijg je eigenlijk een leeg paneel
![image](https://user-images.githubusercontent.com/29454303/103338633-4ee71080-4a7f-11eb-9066-d7e5fd5e20a3.png)

De site sheet mag enkel (programmatisch) openen wanneer de gebruiker een feature op onze kaart aanklikt en er relevante data kan worden getoond.
 
Merk ook op dat het toggle gedrag niet volledig werd doorgevoerd, "Venster sluiten" blijft aanwezig ook als de functie van de knop openen is:
```
<button is="vl-button" type="button" class="vl-side-sheet__toggle">
    <span is="vl-icon" data-vl-icon="nav-left"></span>
    <span class="vl-u-visually-hidden">Venster sluiten</span>
</button>
```

Verder heb ik ook gemerkt dat de tekst nu een pak lager begint (zie "Details" in screenshots) maar ik neem aan dat dit gewenste weergave van de nieuwe huisstijl is.

**Gewenst gedrag**
Side sheet die volledig verborgen is wanneer er geen context is. Mits een introductie van een nieuw attribuut zou de mogelijk kunnen zijn.

**Omgeving (gelieve aan te vullen):**
 - Browser any
 - Versie component  3.1.2

**Extra info**
De vl-map-side-sheet werd aanbevolen, maar op het eerste zicht (zonder effectief te proberen) lijkt deze hetzelfde gedrag te hebben.

**Comment by coemans** [comment]
### Algemeen
Er zijn momenteel 2 varianten van de vl-side-sheet.

**Normale variant**
De normale variant wordt fixed op pagina niveau getoond en voegt automatisch een witruimte buffer toe voor de global header. Op basis van het screenshot vermoed ik dat niet de centrale global header gebruikt wordt, waardoor er overbodig extra witruimte zichtbaar is.

<img width="2560" alt="screenshot" src="https://user-images.githubusercontent.com/11139249/106017140-73ef9300-60c0-11eb-9a3c-d9fa1a70d770.png">

Ik vermoed dat zeer binnenkort de nieuwe global header gebruikt kan worden of in afwachting zelfs de oude global header toegepast kan worden en er daardoor geen extra uitbreiding nodig is aan de webcomponent om het tijdelijk witruimte probleem op te lossen.

**Absolute gepositioneerde variant**
De absoluut gepositioneerde variant wordt typisch binnen een ander element getoond zoals bijvoorbeeld de vl-map-side-sheet bij de vl-map als kaart zijpaneel. Deze variant heeft geen extra witruimte voorzien voor de header.

<img width="2560" alt="screenshot-absolute" src="https://user-images.githubusercontent.com/11139249/106017739-160f7b00-60c1-11eb-8ee3-530e40a7a8f2.png">

### Toggle knop
Aangezien de context hier een kaart betreft, zou eigenlijk best de vl-map-side-sheet component gebruikt worden. Indien door omstandigheden niet mogelijk kan er altijd overgeschakeld worden naar de absolute variant.

Er werd een toggle knop geïntroduceerd. Ik ben niet volledig op de hoogte van de context waarin deze component gebruikt wordt, maar ik denk niet dat het op zich een probleem moet zijn dat de gebruiker het zijpaneel kan openen zonder eerst een feature te selecteren. De gebruiker zou dan tekstueel op de hoogte gebracht kunnen worden dat hij een feature moet selecteren op de kaart om de details hiervan te bekijken. Indien dit geen optie is, kan de vl-side-sheet applicatief pas toegevoegd worden aan de kaart na selectie van een feature. Hierdoor is de vl-side-sheet en bijgevolg ook de toggle knop niet zichtbaar wanneer er geen feature geselecteerd werd.

### Bug
Het venster sluiten probleem zal in kader van dit issue opgepikt en opgelost worden.

**Comment by driesva** [comment]
Toen de applicatie destijds gebouwd werd, bestond er slechts 1 variant. Onze scope was nu beperkt tot het upgraden van bestaande componenten (ervan uit gaande dat de functionaliteit identiek was).

Ik zal een actie loggen aan onze kant om:
- te switchen naar vl-map-side-sheet
- de side sheet niet te renderen indien er geen features zijn geselecteerd (een tekst lijkt geen goed idee aangezien je niet altijd weet of er effectief features zijn op de kaart op basis van profiel gebruiker).
